name: Xingxiu Daily Sync

on:
  schedule:
    # Jakarta 01:30 = UTC 18:30 (previous day)
    - cron: "30 18 * * *"
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Jakarta
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}   # 设置为 xingxiu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r daily_sync/requirements.txt
      - name: Run sync (Jakarta yesterday)
        run: python daily_sync/sync_xingxiu_data.py
