name: Daily Sync Xingxiu

on:
  schedule:
    # Jakarta 01:30 = UTC 18:30 (上一日)
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}   # 设成你的库名（例如 xingxiu_db）
          API_KEY: ${{ secrets.API_KEY }}   # 若接口需要 key，就设置；不需要可不配
        run: python sync_xingxiu_data.py
